import { callableFireFunction } from '@/utils/callableFireFunction'

import type { CalendarEvent } from '@/types'

const getCalendarEvents = async (
	farmUuid: string,
	startDate?: string,
	endDate?: string,
	date?: string
) => {
	// API requires either 'date' OR both 'startDate' and 'endDate', but not both combinations
	let requestParams: any

	if (date) {
		// Get events for a specific day
		requestParams = {
			operation: 'getCalendarEvents',
			farmUuid,
			date,
		}
	} else if (startDate && endDate) {
		// Get events for a date range
		requestParams = {
			operation: 'getCalendarEvents',
			farmUuid,
			startDate,
			endDate,
		}
	} else {
		throw new Error('Either date or both startDate and endDate must be provided')
	}

	try {
		const response = await callableFireFunction<{
			success: boolean
			data: CalendarEvent[]
			count: number
		}>('calendar', requestParams)

		return response.data
	} catch (error) {
		console.error('Error calling calendar API:', error)
		throw error
	}
}

const getCalendarEventByUuid = async (eventUuid: string): Promise<CalendarEvent> => {
	const response = await callableFireFunction<{
		success: boolean
		data: CalendarEvent
	}>('calendar', {
		operation: 'getCalendarEventByUuid',
		eventUuid,
	})
	return response.data
}

const createCalendarEvent = async (
	eventData: Omit<CalendarEvent, 'uuid' | 'createdAt' | 'updatedAt' | 'farmUuid' | 'createdBy'>,
	userUuid: string,
	farmUuid: string
): Promise<{ uuid: string; isNew: boolean }> => {
	const response = await callableFireFunction<{
		success: boolean
		data: { uuid: string; isNew: boolean }
	}>('calendar', {
		operation: 'upsertCalendarEvent',
		eventData: {
			...eventData,
			farmUuid,
			createdBy: userUuid,
			isAutoGenerated: eventData.isAutoGenerated || false,
			status: eventData.status || 'pending',
		},
		userUuid,
	})
	return response.data
}

const updateCalendarEvent = async (
	eventData: Partial<CalendarEvent> & { uuid: string },
	userUuid: string
) => {
	const response = await callableFireFunction<{
		success: boolean
		data: { uuid: string; isNew: boolean }
	}>('calendar', {
		operation: 'upsertCalendarEvent',
		eventData,
		userUuid,
	})
	return response.data
}

const updateCalendarEventStatus = async (
	eventUuid: string,
	status: CalendarEvent['status'],
	updatedBy: string
) => {
	const response = await callableFireFunction<{ success: boolean }>('calendar', {
		operation: 'updateCalendarEventStatus',
		eventUuid,
		status,
		updatedBy,
	})
	return response
}

const deleteCalendarEvent = async (eventUuid: string, userUuid: string) => {
	const response = await callableFireFunction<{ success: boolean }>('calendar', {
		operation: 'deleteCalendarEvent',
		eventUuid,
		deletedBy: userUuid,
	})
	return response
}

export const CalendarService = {
	getCalendarEvents,
	getCalendarEventByUuid,
	createCalendarEvent,
	updateCalendarEvent,
	updateCalendarEventStatus,
	deleteCalendarEvent,
}
