interface CalendarEvent {
	uuid: string
	farmUuid: string
	title: string
	description: string
	date: string // YYYY-MM-DD format
	time?: string // HH:MM format
	type: 'birth' | 'drying' | 'medication' | 'checkup' | 'task' | 'custom'
	priority: 'low' | 'medium' | 'high'
	status: 'pending' | 'completed' | 'cancelled' | 'overdue'
	relatedType?: 'animal' | 'task' | 'health_record'
	relatedId?: string
	isAutoGenerated: boolean
	createdBy: string
	createdAt?: string
	updatedAt?: string
}

interface CalendarDay {
	date: string // YYYY-MM-DD
	events: CalendarEvent[]
	isToday: boolean
	isCurrentMonth: boolean
}

interface CalendarMonth {
	year: number
	month: number // 0-11
	days: CalendarDay[]
}

interface CalendarFilters {
	types: CalendarEvent['type'][]
	priorities: CalendarEvent['priority'][]
	status: CalendarEvent['status'][]
	animalUuid?: string
}
