export interface CalendarEvent {
	uuid: string
	farmUuid: string
	title: string
	description: string
	date: string
	time?: string
	type: 'birth' | 'drying' | 'medication' | 'checkup' | 'task' | 'custom'
	priority: 'low' | 'medium' | 'high' | 'critical'
	status: 'pending' | 'completed' | 'cancelled' | 'overdue'
	relatedType?: 'animal' | 'task' | 'health_record'
	relatedId?: string
	isAutoGenerated: boolean
	reminder: boolean
	reminderMinutes: number[]
	createdBy: string
	createdAt?: string
	updatedAt?: string
}

export interface CalendarDay {
	date: string
	events: CalendarEvent[]
	isToday: boolean
	isCurrentMonth: boolean
}

export interface CalendarMonth {
	year: number
	month: number
	days: CalendarDay[]
}

export interface CalendarFilters {
	types: CalendarEvent['type'][]
	priorities: CalendarEvent['priority'][]
	status: CalendarEvent['status'][]
	animalUuid?: string
}
