import { z } from 'zod'

export const calendarEventSchema = z.object({
	uuid: z.string().optional(),
	farmUuid: z.string().optional(),
	title: z
		.string()
		.min(1, 'calendar:form.errors.titleRequired')
		.min(3, 'calendar:form.errors.titleTooShort'),
	description: z.string().optional(),
	type: z.enum(['task', 'medication', 'checkup', 'birth', 'drying', 'custom']),
	priority: z.enum(['critical', 'high', 'medium', 'low']),
	date: z.string().min(1, 'calendar:form.errors.dateRequired'),
	time: z.string().optional(),
	relatedType: z.enum(['animal', 'task', 'health_record']).optional(),
	relatedId: z.string().optional(),
	status: z.enum(['pending', 'completed', 'cancelled', 'overdue']),
	isAutoGenerated: z.boolean(),
	createdAt: z.string().optional(),
	updatedAt: z.string().optional(),
	createdBy: z.string().optional(),
})

export type CalendarEventFormData = z.infer<typeof calendarEventSchema>
